### ISSUE TITLE
Operations of Singly Linked List in CPP

### ISSUE THREAD

**Issue by Vanshika-Batra** [theonlyanson/Hacktoberfest-2022#239]
Hey @theonlyanson! I'd like to contribute by adding the code of the following programs:
- Insertion in Linked List
- Deletion in Linked List
- Reversal of Linked List
Kindly assign them to me under Hacktoberfest2022 label.

**Comment by theonlyanson** [comment]
> Hey @theonlyanson! I'd like to contribute by adding the code of the following programs:
> - Insertion in Linked List
> - Deletion in Linked List
> - Reversal of Linked List
> Kindly assign them to me under Hacktoberfest2022 label.

Ok go on
