### ISSUE TITLE
Searching an element in the Linked List in CPP

### ISSUE THREAD

**Issue by Vanshika-Batra** [theonlyanson/Hacktoberfest-2022#259]
Hey @theonlyanson! I'd like to contribute by adding the program "Searching for an element in the linked list" in C++ under the Linked List folder. Kindly assign this to me under the Hacktoberfest2022 tag.

**Comment by theonlyanson** [comment]
> Hey @theonlyanson! I'd like to contribute by adding the program "Searching for an element in the linked list" in C++ under the Linked List folder. Kindly assign this to me under the Hacktoberfest2022 tag.

Go on
