### ISSUE TITLE
Web Landing Page

### ISSUE THREAD

**Issue by Gaurika-Gupta** [theonlyanson/Hacktoberfest-2022#286]
Using HTML, CSS, JS

**Comment by Gaurika-Gupta** [comment]
Please assign me this issue under Hacktoberfest 2022 after adding necessary labels

**Comment by Shreyask142002** [comment]
okayyy

**Comment by prabhleenn** [comment]
Hello sir, Can I work on this issue please ?

**Comment by Shreyask142002** [comment]
yes okayyyyyy
